language: java
jdk:
- openjdk7
- oraclejdk8
sudo: false
before_install:
- cp ./etc/settings.xml ~/.m2/
- cp ./etc/onFailure.sh  ~/
- cp ./etc/onSuccess.sh  ~/
- chmod 777 ~/onFailure.sh
- chmod 777 ~/onSuccess.sh
script:
- mvn -B clean verify
after_failure: ~/onFailure.sh
after_success: ~/onSuccess.sh
after_script:
- mvn -B cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
  on_success: always
env:
  global:
  - secure: PFFLZ5ktK8DNxz7eluxjbSDo90Lk/+58zuuhdPJ67JR9nu0WDw+M78/26h5I3EwLAzMV78lNo7ASVQd04l6z89QEncwgEfwO/sO8ZL4vkdIZWw1+1z0Lxk4WDzNhqE9p1KK85NSxZsG5yOfTWaYOcHzv2cCRGwlODSCjL+c3XTMpSFoggVO3XFz/1csqeUN0YOqlCkRZPRvnYsKNQK/sQZLqYucZ3qMlkiMQcwnRA7ObQatSiR8YRSLrxjMvYyo+69IZg+pi2r2rNla5Q8jpAbFH017U7elbuUs9NTfRCWCzunmIEQAuUqFan6Gjc3X0HjIK2QWsmHfuGB+ZwkXieJEmXxi8QWxH16uVa7gIpuwIav6IAqeiN63vweak6NBXLSdn9ZeauGDjV3Xu8ryM+axZAw+0FeqCNOYy5ukQg+l7uilXM/1wJ8HfH1EkzgM4Ejo3tjMKogplUDHWrvoBhTWEZ7awvq8kNy8Ur4WNQJ6gy/hM09v7G2XiEYoEILLTEbrAt6oAJ48xSaNEWxCCwjtS/gNkWRHoH2Sclflr/HeaaBqBitYwwD548yHHOXuiOPviiwi5e+XxY1Uv6JcFSzaCesJSFcI+VKnCBU3wRjjJsdM/jSBz6hW2OpaXUt+Y828D/juU4d+p/F9t1VH2x946ZKREcVNBMkzZ2YJck0Y=
  - secure: UJtXIsQ5mpFm0z4w4DJdvpq1z2RjXZQgXibDyjRebL791AclnGI+uRKhHBEtg2FMNM+94fZn+ANi1zmrChnhsTKXHOc3vyoO9eOvljzIe4x8Bh8IW/FUf1CHCeu6aeOBj6fR20p+biOJIaYXHB32q6CZv4yVNgZdG3UaIrJXxumuypSxcReHdYbM7GRSdKDdgOmpA2acHEt0DM6G2PWftbRFH4EeJkco//yEQo8RmN4zeYJol/2peK/8S0uM6jU2wWwbeg/ivjIFC8yJXUQbJExQ9N6qmiDNmcm4zrekdKWEvHqyL/lyzjXS6x0om4vNfRn2BAzA4iAVU9QXcx3g/vjrZIRz1vF+Yowuf5cYowUrDfIIp/Jd+o4HX3LIE0zwYClScRzX1NHRYRjKpsNjKxb1NxEkOGKUW72moTbTkGUgtYIGQryXt/E4tYBdS/p70rX7Yaa+hGGcNAVnk7QwgVJeRlYXEQ47cy0Bc0+/zkyPOqkjMzwb6APojIYGdr/Rfmr1CnyYMQ4yNw0FI1tgy5cnouVc2o6zKSP9MCoB3yeoRMhRbu+QemakU5zJ71wMlZ4Zp5c0lUoMUzJoJNwZ9CHTMY4ZQXtPPGiGQwkEk6SNjQMdrAnLYn1ywAJzyEUeiDTtzdG67D99v5ueCtZLueAhzWlC6mtTWKWvG3gOGqo=
